[profile.default]
src = 'src/selected'
out = 'out'
libs = ['lib']
test = 'test'
solc = '0.8.26'
evm_version = 'cancun'
optimizer = true
optimizer_runs = 833
via_ir = true

[fmt]
line_length = 120
tab_width = 4
