[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
evm_version = 'cancun'
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
bsc = "https://bnb-mainnet.g.alchemy.com/v2/G7aI_S2zB8Ue317Wtph2vnzucBj_k6Tw"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/G7aI_S2zB8Ue317Wtph2vnzucBj_k6Tw"
