[profile.default]
src = 'src/traitforge/contracts/TraitForgeNft'
out = 'out'
libs = ['lib']
test = 'test'
evm_version = 'cancun'
fs_permissions = [{ access = "read", path = "./" }]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts-v4/", "@openzeppelin/contracts/=lib/openzeppelin-contracts-v4/contracts/"]

[fmt]
line_length = 120
tab_width = 4
