[profile.default]
src = 'src/ajna/src'
out = 'out'
libs = ['lib']
test = 'test'
evm_version = 'paris'
optimizer = true
optimizer_runs = 500
remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/',
  '@prb-math/=lib/prb-math/',
  '@clones/=lib/clones-with-immutable-args/src/',
  '@base64-sol/=lib/base64/'
]

[fmt]
line_length = 120
tab_width = 4
