[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
evm_version = 'cancun'
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
bsc = "https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3"
base = "https://base.gateway.tenderly.co"
mainnet = "https://eth.drpc.org"

[fmt]
line_length = 120
tab_width = 4
