[profile.default]
src = 'src/selected'
out = 'out'
libs = ['lib']
test = 'test'
evm_version = 'cancun'
solc = '0.8.19'
fs_permissions = [{ access = "read", path = "./" }]

[fmt]
line_length = 120
tab_width = 4
