[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
evm_version = 'cancun'
via_ir = true
optimizer = true
fs_permissions = [{ access = "read", path = "./"}]

[fmt]
line_length = 120
tab_width = 4
